### PR TITLE
Map UI tweaks

### PR DESCRIPTION
**Pull request by nyrocron**
More compact UI. This particular change makes the pilot list tab in the system details much more compact. Also removed a 20px margin-left for the system details and moved the scrollmenu to 2px from the left border for all browsers.

Screenshot of the new pilot list style:

### CODE REVIEW

**Comment by nyrocron** [comment]
Added fix of wormhole type form in the add system dialog.
(Checkboxes and labels were not always in the same line.)
Now looks like this:

**Comment by Zumochi** [comment]
Nice work!

I think these are two separate issues, so I'd either make another PR or update the description to reflect the 2nd feature change as well :+1:

**Comment by nyrocron** [comment]
Renamed PR, splitting it up really doesn't seem worth it unless either part isn't accepted.

**Comment by Zumochi** [comment]
Much luffs :heart:

**Pull request merged**
