### PR TITLE
Wormhole name fix, added new wormholes

### PR DESCRIPTION
**Pull request by Zumochi**
See commits!

You may want to cherry-pick and leave out the new wormholes until they are actually confirmed/released on Tranquility.

### CODE REVIEW

**Comment by nyrocron** [comment]
Is there a reason for changing indentation from 4 to 2 spaces?

**Comment by Zumochi** [comment]
No particular reason. Do these indentation rules also apply to JSON then? If so, I'll fix it up to 4 spaces.

I couldn't find a indentation standard for JSON so I left it with my IDE's default.

**Comment by marbindrakon** [comment]
First off, thanks for your contribution. I'm going to wait until closer to TQ release to merge this in since I suspect there will be more data to adjust.

I use dumpdata to generate the fixtures instead of editing by hand. The indentation isn't a standard, I just always use indent=4 when generating them out of habit. I will be regenerating your fixtures as part of merging this so it will end up going back to 4.

Another thing to consider is that only objects with a new pk field will be added when loading fixtures on an existing database, so we need to add a data migration to fix the name as well as correcting the fixtures. I'll handle that as part of merging this in as migrations are going to change in the next release to use Django's new built-in system.

**Comment by Zumochi** [comment]
OK! Cool!

Speaking of the next release, are there any plans to change the built-in webserver to be uwsgi? I have been seeing (deprecation?) warning messages that say to use uwsgi (I think?) instead of gunicorn as well (or it might just be a different method to start the workers).
Sadly I can't seem to find these messages at the moment :( Will get back when I see them again.

**Comment by marbindrakon** [comment]
Whether you use gunicorn or uwsgi is more personal choice. I use gunicorn so I wrote the docs with gunicorn. The code shouldn't care one way or the other.

**Comment by Zumochi** [comment]
Either way it recommended a different approach of starting the workers. But closing PR for the reasons you mentioned earlier :)

**Pull request closed without merging**
