### PR TITLE
Issue #123: Lots of new features

### PR DESCRIPTION
**Pull request by proycon**
This is a full pull request,  you may prefer to cherry-pick rather than adopt all of it:
 - map scaling
 - different style  (eol is dashed yellow, frig holes white)
 - wh effects show in border and in label
 - zen mode (calmer colours, less information)
 - pilot names under nodes   (disabled notification ring)
 - easily accessible jump to top button
 - coloured signatures by type
 - no tabs for system details, all in one view (saves clicks)
 - bulk import is no separate window anymore (saves clicks)
 - silent mapping enabled by default
 - removed autopilot waypoints, they cluttered the interface and we didn't use them
 - changed icon for "you are here" (our corp logo ;) )

### CODE REVIEW

**Comment by Zumochi** [comment]
Do you have some pictures? :)

**Comment by proycon** [comment]
Yes, see https://github.com/marbindrakon/eve-wspace/issues/123

**Comment by proycon** [comment]
New pilot list is now a toggle and can be switched on/off

**Comment by marbindrakon** [comment]
I finally got a chance to take a first pass at merging this in (see the proycon-merge branch). So far, I've reverted the imae changes, changed the scale buttons to a slider, and fixed some bugs in the Set Danger button. 

I'm still not convinced about the all-in-one system details setup. I think I'll need to finally finish the options system and make it optional.

**Comment by proycon** [comment]
Thanks, very nice with the slider!

**Pull request closed without merging**
